[package]
name = "prust_core"
version = "0.1.0"
authors = ["syelman <selman.ozleyen2017@gtu.edu.tr>"]
edition = "2018"

[dependencies]
byteorder = {version = "1.3.4", default-features = false }
libc = "0.2.0"
hashbrown = "0.8.2"
arrayvec = {version ="0.5.1", default-features = false}
arrayref = "0.3.6"
